services:
  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: weather
      POSTGRES_USER: BiwBong
      POSTGRES_PASSWORD: Biwrescue1706
      TZ: Asia/Bangkok
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: weather@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  db:
  